export const ROUTES = {
  HOME: '/',
  ADMIN_TOURNAMENTS: '/admin/torneos',
  ADMIN_TOURNAMENTS_SHOW: (id: string) => `/admin/torneos/${id}`,
  ADMIN_TOURNAMENTS_CREATE: '/admin/torneos/crear',
  ADMIN_TOURNAMENTS_EDIT: (id: string) => `/admin/torneos/editar/${id}`,
  ADMIN_CATEGORIES: '/admin/categorias',
  ADMIN_CATEGORIES_CREATE: '/admin/categorias/crear',
  ADMIN_CATEGORIES_EDIT: (id: string) => `/admin/categorias/editar/${id}`,
  ADMIN_TEAMS: '/admin/equipos',
  ADMIN_TEAM_CREATE: '/admin/equipos/crear',
  ADMIN_TEAMS_SHOW: (id: string) => `/admin/equipos/${id}`,
  ADMIN_TEAM_EDIT: (id: string) => `/admin/equipos/editar/${id}`,
  ADMIN_FIELDS: '/admin/canchas',
  ADMIN_FIELD_CREATE: '/admin/canchas/crear',
  ADMIN_FIELDS_SHOW: (id: string) => `/admin/canchas/${id}`,
  ADMIN_FIELD_EDIT: (id: string) => `/admin/canchas/editar/${id}`,
  ADMIN_COACHES: '/admin/entrenadores',
  ADMIN_COACHES_SHOW: (id: string) => `/admin/entrenadores/perfil/${id}`,
  ADMIN_PLAYERS: '/admin/jugadores',
  ADMIN_PLAYERS_CREATE: '/admin/jugadores/crear',
  ADMIN_PLAYERS_EDIT: (id: string) => `/admin/jugadores/editar/${id}`,
  ADMIN_PLAYER: (id: string) => `/admin/jugadores/perfil/${id}`,
  ADMIN_MATCHES: '/admin/encuentros',
  ADMIN_MATCHES_CREATE: '/admin/encuentros/crear',
  ADMIN_MATCHES_SHOW: (id: string) => `/admin/encuentros/${id}`,
  ADMIN_MATCHES_EDIT: (id: string) => `/admin/encuentros/editar/${id}`,
  ADMIN_PLAYOFFS: '/admin/liguilla',
  ADMIN_PLAYOFFS_CREATE: '/admin/liguilla/crear',
  ADMIN_PLAYOFFS_SHOW: (id: string) => `/admin/liguilla/${id}`,
  ADMIN_PLAYOFFS_EDIT: (id: string) => `/admin/liguilla/editar/${id}`,
  ADMIN_PLAYOFFS_MATCHES: (id: string) => `/admin/liguilla/${id}/encuentros`,
  ADMIN_PLAYOFFS_MATCHES_CREATE: (id: string) => `/admin/liguilla/${id}/encuentros/crear`,
  ADMIN_PLAYOFFS_MATCHES_SHOW: (playoffId: string, matchId: string) => {
    return `/admin/liguilla/${playoffId}/encuentros/detalles/${matchId}`;
  },
  ADMIN_PLAYOFFS_MATCHES_EDIT: (playoffId: string, matchId: string) => {
    return `/admin/liguilla/${playoffId}/encuentros/editar/${matchId}`;
  },
  ADMIN_STANDINGS: '/admin/estadisticas',
  ADMIN_PAGES: '/admin/paginas',
  ADMIN_BANNERS: '/admin/banners',
  ADMIN_GALLERIES: '/admin/galerias',
  ADMIN_GALLERIES_CREATE: '/admin/galerias/crear',
  ADMIN_GALLERIES_SHOW: (id: string) => `/admin/galerias/${id}`,
  ADMIN_GALLERIES_EDIT: (id: string) => `/admin/galerias/editar/${id}`,
  ADMIN_USERS: '/admin/usuarios',
  ADMIN_USERS_SHOW: (id: string) => `/admin/usuarios/${id}`,
  ADMIN_USERS_CREATE: '/admin/usuarios/create',
  ADMIN_USERS_EDIT: (id: string) => `/admin/usuarios/editar/${id}`,
  ADMIN_MESSAGES: '/admin/mensajes',
  ADMIN_SPONSORS: '/admin/patrocinadores',
  ADMIN_SPONSORS_CREATE: '/admin/patrocinadores/crear',
  ADMIN_SPONSORS_SHOW: (id: string) => `/admin/patrocinadores/${id}`,
  ADMIN_SPONSORS_EDIT: (id: string) => `/admin/patrocinadores/editar/${id}`,
  ADMIN_ANNOUNCEMENTS: '/admin/noticias',
  ADMIN_ANNOUNCEMENTS_CREATE: '/admin/noticias/crear',
  ADMIN_ANNOUNCEMENTS_SHOW: (id: string) => `/admin/noticias/${id}`,
  ADMIN_ANNOUNCEMENTS_EDIT: (id: string) => `/admin/noticias/editar/${id}`,
  PUBLIC_ANNOUNCEMENTS: '/noticias',
  PUBLIC_ANNOUNCEMENTS_SHOW: (id: string) => `/noticias/${id}`,
  ADMIN_VIDEOS: '/admin/videos',
  ADMIN_VIDEOS_CREATE: '/admin/videos/crear',
  ADMIN_VIDEOS_SHOW: (id: string) => `/admin/videos/${id}`,
  ADMIN_VIDEOS_EDIT: (id: string) => `/admin/videos/editar/${id}`,
  PUBLIC_VIDEOS: '/videos',
  PUBLIC_VIDEOS_SHOW: (id: string) => `/videos/${id}`,
  PUBLIC_TOURNAMENTS: '/torneos',
  PUBLIC_TOURNAMENT_SHOW: (permalink: string) => `/torneos/${permalink}`,
  PUBLIC_TEAMS: '/equipos',
  PUBLIC_TEAMS_SHOW: (permalink: string) => `/equipos/${permalink}`,
  PUBLIC_RESULTS: '/resultados',
  PUBLIC_CONCENTRATED: '/concentrado',
  PUBLIC_STANDINGS: '/estadisticas',
  PUBLIC_IMAGES: '/imagenes',
  PUBLIC_CONTACT: '/contacto',
} as const;
