export const ROUTES = {
  HOME: '/',
  ADMIN_TOURNAMENTS: '/admin/torneos',
  ADMIN_TEAMS: '/admin/equipos',
  ADMIN_TEAM_CREATE: '/admin/equipos/crear',
  ADMIN_TEAM: (id: string) => `/admin/equipos/${id}`,
  ADMIN_TEAM_EDIT: (id: string) => `/admin/equipos/editar/${id}`,
  ADMIN_FIELDS: '/admin/canchas',
  ADMIN_FIELD_CREATE: '/admin/canchas/crear',
  ADMIN_FIELD: (id: string) => `/admin/canchas/${id}`,
  ADMIN_FIELD_EDIT: (id: string) => `/admin/canchas/editar/${id}`,
  ADMIN_COACHES: '/admin/entrenadores',
  ADMIN_PLAYERS: '/admin/jugadores',
  ADMIN_PLAYERS_CREATE: '/admin/jugadores/crear',
  ADMIN_PLAYERS_EDIT: (id: string) => `/admin/jugadores/editar/${id}`,
  ADMIN_PLAYER: (id: string) => `/admin/jugadores/perfil/${id}`,
  ADMIN_MATCHES: '/admin/encuentros',
  ADMIN_MATCHES_CREATE: '/admin/encuentros/crear',
  ADMIN_MATCHES_EDIT: (id: string) => `/admin/encuentros/editar/${id}`,
  ADMIN_MATCH: (id: string) => `/admin/encuentros/detalles/${id}`,
  ADMIN_STANDINGS: '/admin/estadisticas',
  ADMIN_PAGES: '/admin/paginas',
  ADMIN_BANNERS: '/admin/banners',
  ADMIN_GALLERIES: '/admin/galerias',
  ADMIN_GALLERIES_CREATE: '/admin/galerias/crear',
  ADMIN_GALLERIES_SHOW: (id: string) => `/admin/galerias/${id}`,
  ADMIN_GALLERIES_EDIT: (id: string) => `/admin/galerias/editar/${id}`,
  ADMIN_USERS: '/admin/usuarios',
  ADMIN_MESSAGES: '/admin/mensajes',
  ADMIN_SPONSORS: '/admin/patrocinadores',
  ADMIN_SPONSORS_CREATE: '/admin/patrocinadores/crear',
  ADMIN_SPONSORS_SHOW: (id: string) => `/admin/patrocinadores/${id}`,
  ADMIN_SPONSORS_EDIT: (id: string) => `/admin/patrocinadores/editar/${id}`,
  ADMIN_ANNOUNCEMENTS: '/admin/noticias',
  ADMIN_ANNOUNCEMENTS_CREATE: '/admin/noticias/crear',
  ADMIN_ANNOUNCEMENTS_SHOW: (id: string) => `/admin/noticias/${id}`,
  ADMIN_ANNOUNCEMENTS_EDIT: (id: string) => `/admin/noticias/editar/${id}`,
  PUBLIC_ANNOUNCEMENTS: '/noticias',
  PUBLIC_ANNOUNCEMENTS_SHOW: (id: string) => `/noticias/${id}`,
  ADMIN_VIDEOS: '/admin/videos',
  ADMIN_VIDEOS_CREATE: '/admin/videos/crear',
  ADMIN_VIDEOS_SHOW: (id: string) => `/admin/videos/${id}`,
  ADMIN_VIDEOS_EDIT: (id: string) => `/admin/videos/editar/${id}`,
  PUBLIC_VIDEOS: '/videos',
  PUBLIC_VIDEOS_SHOW: (id: string) => `/videos/${id}`,
} as const;
