import type { CoachSeed } from "@/shared/interfaces";

export const coaches: CoachSeed[] = [
  {
    name: 'José Martínez López',
    email: 'jose456@gmail.com',
    phone: '335-678-9012',
    age: 52,
    nationality: 'Mexicana',
    imageUrl: null,
    imagePublicID: null,
    description: 'Entrenador con más de 25 años de experiencia en formación de jóvenes talentos y desarrollo de equipos competitivos.',
    active: true,
    teamIds: [],
  },
  {
    name: 'Alejandro Ruiz Ramírez',
    email: 'alex432@gmail.com',
    phone: '336-789-0123',
    age: 38,
    nationality: 'Brasileña',
    imageUrl: null,
    imagePublicID: null,
    description: 'Entrenador especializado en tácticas ofensivas y desarrollo técnico, con experiencia en ligas juveniles de Brasil y México.',
    active: true,
    teamIds: [],
  },
  {
    name: 'Carlos Fernández Gómez',
    email: 'carlos123@hotmail.com',
    phone: '337-890-1234',
    age: 45,
    nationality: 'Mexicana',
    imageUrl: null,
    imagePublicID: null,
    description: 'Entrenador con amplia experiencia en formación de porteros y estrategias defensivas, habiendo trabajado con varios equipos juveniles en México.',
    active: false,
    teamIds: [],
  },
  {
    name: 'Jennifer Brown',
    email: 'jennifer432@gmail.com',
    phone: '338-901-2345',
    age: 29,
    nationality: 'Estadounidense',
    imageUrl: null,
    imagePublicID: null,
    description: 'Entrenadora enfocada en el desarrollo integral de jugadoras jóvenes, promoviendo la igualdad de género en el deporte y técnicas modernas de entrenamiento.',
    active: true,
    teamIds: [],
  }
];