import { PlayerSeed } from "@/shared/interfaces";

export const players: PlayerSeed[] = [
  {
    name: 'Raul Dominguez Pérez',
    email: 'raul342@gmail.com',
    phone: '335-678-8901',
    nationality: 'Mexicana',
    birthday: new Date('2012-05-15'),
    imageUrl: null,
    imagePublicID: null,
    active: true,
    teamId: null,
  },
  {
    name: 'Miguel Ángel López García',
    email: 'miguel342@gmail.com',
    phone: '445-789-0123',
    nationality: 'Mexicana',
    birthday: new Date('2012-02-08'),
    imageUrl: null,
    imagePublicID: null,
    active: true,
    teamId: null,
  },
  {
    name: 'Fernando Duran Martínez',
    email: 'fernando342@gmail.com',
    phone: '556-890-1234',
    nationality: 'Mexicana',
    birthday: new Date('2012-08-22'),
    imageUrl: null,
    imagePublicID: null,
    active: true,
    teamId: null,
  },
  {
    name: 'Javier Sánchez Ruiz',
    email: 'javier789@gmail.com',
    phone: '555-222-3333',
    nationality: 'Mexicana',
    birthday: new Date('2013-02-08'),
    imageUrl: null,
    imagePublicID: null,
    active: true,
    teamId: null,
  },
  {
    name: 'Alejandra Torres Fernández',
    email: 'alex567@gmail.com',
    phone: '444-555-6666',
    nationality: 'Mexicana',
    birthday: new Date('2013-08-12'),
    imageUrl: null,
    imagePublicID: null,
    active: true,
    teamId: null,
  },
  {
    name: 'Julieta Ramirez Arechiga',
    email: 'julieta123@outlook.com',
    phone: '777-888-9999',
    nationality: 'Mexicana',
    birthday: new Date('2012-04-08'),
    imageUrl: null,
    imagePublicID: null,
    active: true,
    teamId: null,
  },
  {
    name: 'Karla Vazquez Mendoza',
    email: 'karla123@yahoo.com',
    phone: '222-333-4444',
    nationality: 'Mexicana',
    birthday: new Date('2012-06-12'),
    imageUrl: null,
    imagePublicID: null,
    active: true,
    teamId: null,
  },
  {
    name: 'Lorena Lopez Castillo',
    email: 'lorena123@yahoo.com',
    phone: '111-222-3333',
    nationality: 'Mexicana',
    birthday: new Date('2012-09-15'),
    imageUrl: null,
    imagePublicID: null,
    active: true,
    teamId: null,
  },
];