import type { TeamSeed } from "@/shared/interfaces/Team";

export const teams: TeamSeed[] = [
  {
    name: 'Leones Negros Base Area',
    permalink: 'leones-negros-base-area',
    headquarters: 'Base Area',
    imageUrl: null,
    imagePublicID: null,
    division: '2016',
    group: '9 vs 9',
    country: 'México',
    city: 'Zapopan',
    state: 'Jalisco',
    emails: ['leones_negros_base_aerea@gmail.com'],
    address: null,
    active: true,
    tournamentId: '',
    coachId: '',
  },
  {
    name: 'Club Country',
    permalink: 'club-country',
    headquarters: 'Club Country',
    imageUrl: null,
    imagePublicID: null,
    division: '2016',
    group: '9 vs 9',
    country: 'México',
    city: 'Zapopan',
    state: 'Jalisco',
    emails: ['club_country@gmail.com'],
    address: null,
    active: true,
    tournamentId: '',
    coachId: '',
  },
  {
    name: 'Linces FC',
    permalink: 'club-linces-fc',
    headquarters: 'Linces',
    imageUrl: null,
    imagePublicID: null,
    division: '2016',
    group: '9 vs 9',
    country: 'México',
    city: 'Zapopan',
    state: 'Jalisco',
    emails: ['linces_club@gmail.com'],
    address: null,
    active: true,
    tournamentId: '',
    coachId: '',
  },
  {
    name: 'Diablos Rojos',
    permalink: 'diablos-rojos',
    headquarters: 'Diablos Rojos',
    imageUrl: null,
    imagePublicID: null,
    division: '2016',
    group: '9 vs 9',
    country: 'México',
    city: 'Guadalajara',
    state: 'Jalisco',
    emails: ['diablos_rojos@gmail.com'],
    address: null,
    active: true,
    tournamentId: '',
    coachId: '',
  },
  {
    name: 'Club Occidental',
    permalink: 'club-occidental',
    headquarters: 'Club Occidental',
    imageUrl: null,
    imagePublicID: null,
    division: '2016',
    group: '9 vs 9',
    country: 'México',
    city: 'Guadalajara',
    state: 'Jalisco',
    emails: ['club_occidental_fc@gmail.com'],
    address: null,
    active: true,
    tournamentId: '',
    coachId: '',
  },
  {
    name: 'Halcones Dorados',
    permalink: 'halcones-dorados',
    headquarters: 'Halcones Dorados',
    imageUrl: null,
    imagePublicID: null,
    division: '2016',
    group: '9 vs 9',
    country: 'México',
    city: 'Guadalajara',
    state: 'Jalisco',
    emails: ['halcones_dorados@gmail.com'],
    address: null,
    active: true,
    tournamentId: '',
    coachId: '',
  },
  {
    name: 'Colegio Altamira',
    permalink: 'colegio-altamira',
    headquarters: 'Colegio Altamira',
    imageUrl: null,
    imagePublicID: null,
    division: '2016',
    group: '9 vs 9',
    country: 'México',
    city: 'Guadalajara',
    state: 'Jalisco',
    emails: ['colegio_altamira@gmail.com'],
    address: null,
    active: true,
    tournamentId: '',
    coachId: '',
  },
  {
    name: 'Colegio New Land',
    permalink: 'colegio-new-Land',
    headquarters: 'Colegio New Land',
    imageUrl: null,
    imagePublicID: null,
    division: '2016',
    group: '9 vs 9',
    country: 'México',
    city: 'Guadalajara',
    state: 'Jalisco',
    emails: ['colegio_new_land@gmail.com'],
    address: null,
    active: true,
    tournamentId: '',
    coachId: '',
  },
];