import type { TournamentSeed } from "@/shared/interfaces";

export const tournaments: TournamentSeed[] = [
  {
    name: 'Promesas de Mexico 2022',
    permalink: 'promesas-de-mexico-2022',
    imageUrl: null,
    imagePublicID: null,
    description: 'Torneo anual que reúne a equipos juveniles de todo México para competir y mostrar sus habilidades en diversas categorías de edad.',
    country: 'México',
    state: 'Nuevo León',
    city: 'San Nicolás de los Garza',
    season: '2022-2023',
    startDate: new Date(2022, 8, 1),
    endDate: new Date(2022, 10, 24),
    active: false,
  },
  {
    name: 'Torneo Juventud en Acción 2025',
    permalink: 'torneo-juventud-en-accion-2025',
    imageUrl: null,
    imagePublicID: null,
    description: 'Competencia para adolescentes de 13 a 15 años, promoviendo el desarrollo deportivo y valores de trabajo en equipo.',
    country: 'México',
    state: 'Jalisco',
    city: 'Puerto Vallarta',
    season: '2022-2023',
    startDate: new Date(2023, 5, 1),
    endDate: new Date(2023, 7, 24),
    active: false,
  },
  {
    name: 'Torneo Jóvenes Promesas 2025',
    permalink: 'torneo-jovenes-promesas-2025',
    imageUrl: null,
    imagePublicID: null,
    description: 'Torneo formativo para jóvenes talentos, en las categorías infantiles y juveniles menores de 12 años.',
    country: 'México',
    state: 'Jalisco',
    city: 'Guadalajara',
    season: '2025-2026',
    startDate: new Date(2025, 10, 1),
    endDate: new Date(2025, 12, 14),
    active: true,
  },
  {
    name: 'Torneo Pequeños Cachorros 2025',
    permalink: 'torneo-pequenos-cachorros-2025',
    imageUrl: null,
    imagePublicID: null,
    description: 'Torneo recreativo para niños y niñas menores de 8 años, enfocado en la diversión y el aprendizaje del fútbol.',
    country: 'México',
    state: 'Jalisco',
    city: 'Zapopan',
    season: '2025-2026',
    startDate: new Date(2026, 1, 1),
    endDate: new Date(2025, 3, 8),
    active: true,
  },
];
